name: school_attendance_app
description: A comprehensive school attendance management system with facial recognition and geofencing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Code Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^15.2.3
  
  # Camera & Face Recognition
  camera: ^0.11.1
  google_ml_kit: ^0.20.0
  image: ^4.1.3
  
  # Location & Geofencing
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.3
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  
  # Charts & Analytics
  fl_chart: ^1.0.0
  
  # File Operations
  file_picker: ^10.2.0
  csv: ^6.0.0
  pdf: ^3.10.7
  
  # Notifications
  flutter_local_notifications: ^19.3.0
  
  # HTTP & Networking
  http: ^1.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  analyzer: ^7.4.5

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
